[package]
name = "orm_uu"
version = "0.1.0"
edition = "2021"

[lib]
path = "orm_uu/lib.rs"

[dependencies]
macro_lib = {path = "./macro_lib"}
log = "*"
serde_json = { version = "1.0", features = ["preserve_order"] }
common_uu = {git = "https://gitee.com/guoyucode/common_uu.git", default-features = false}
serde = { version = "1.0", features = ["derive"] }
scylla = "0.7"
mysql_async = "0.31"
async-trait = "0.1.60"

[dev-dependencies]
log = "*"
serde_json = { version = "1.0", features = ["preserve_order"] }
common_uu = {git = "https://gitee.com/guoyucode/common_uu.git", default-features = false}
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.13", features = ["rt", "rt-multi-thread", "macros", ] }


# scylladb
scylla = "*"

# redis
redis_cluster_async = {  git = "https://github.com/zhiyong0804/redis-cluster-async.git" }
redis-async-pool = { git = "https://github.com/zhiyong0804/redis-async-pool" }

# mysql
