[package]
name = "orm_mysql_macro"
version = "0.2.0"
edition = "2021"

[lib]
proc-macro = true
path = "./lib.rs"

[dependencies]
log = "0.4"
syn = "1"
quote = "1"
proc-macro2 = "1"
serde_json = { version = "1.0", features = ["preserve_order"] }
common_uu = {version = "1", default-features = false}